server:
  port: 10002
  servlet:
    context-path: /msgProducer

spring:
  application:
    name: msg-producer

eureka:
  client:
    service-url:
      defaultZone: http://yixin:xin123456@192.168.0.112:8000/eurekaServer/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.112
    instance-id: ${eureka.instance.ip-address}:${server.port}
    metadata-map:
      configPath: ${server.servlet.context-path:}

logging:
  level:
    com.netflix: warn
