server:
  port: 10001
  servlet:
    context-path: /serverClint

spring:
  application:
    name: serverClint

management:
  endpoints:
    web:
      exposure:
        include: refresh

logging:
  level:
    com.netflix: warn